#ifndef DATATRANSMISSION_CONFIG_H
#define DATATRANSMISSION_CONFIG_H

#define MAX_TERMINAL_INPUT 5000
#define MAX_CONNECTION_BUTTON_LENGTH 32
#define MAX_LENGTH_IP 16
#define MAX_LENGTH_PORT 6
#define MAX_LENGTH_USERNAME 32
#define MAX_LENGTH_PASSWORD 32

#endif //DATATRANSMISSION_CONFIG_H
