#ifndef DATATRANSMISSION_CONFIG_H
#define DATATRANSMISSION_CONFIG_H

#define MAX_TERMINAL_INPUT           5000
#define MAX_CONNECTION_BUTTON_LENGTH 32
#define MAX_LENGTH_IP                16
#define MAX_LENGTH_PORT              6
#define MAX_LENGTH_USERNAME          32
#define MAX_LENGTH_PASSWORD          32

#define STATE_COMPRESSED   0b00000001
#define STATE_UNCOMPRESSED 0b00000010

#endif //DATATRANSMISSION_CONFIG_H
